// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEh_iouqXd32V_5mD2JTJGwGvt6GUoLLw',
    appId: '1:666971974381:web:b886f769b982445fc1fae4',
    messagingSenderId: '666971974381',
    projectId: 'flutter-gardabooking',
    authDomain: 'flutter-gardabooking.firebaseapp.com',
    storageBucket: 'flutter-gardabooking.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfDNUtk8zZEqNBa5le7Hav98qmhCAMVC4',
    appId: '1:666971974381:android:0938cdf74dba189ac1fae4',
    messagingSenderId: '666971974381',
    projectId: 'flutter-gardabooking',
    storageBucket: 'flutter-gardabooking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcXm4SANZVvsImdhSev6sHOd_8kUkDvug',
    appId: '1:666971974381:ios:544393417a1a71a2c1fae4',
    messagingSenderId: '666971974381',
    projectId: 'flutter-gardabooking',
    storageBucket: 'flutter-gardabooking.appspot.com',
    iosClientId: '666971974381-rbbqiie4694vnq3qt0v3gb9utc0qqc8m.apps.googleusercontent.com',
    iosBundleId: 'henrikferrari.com.ecomrejsegarda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcXm4SANZVvsImdhSev6sHOd_8kUkDvug',
    appId: '1:666971974381:ios:544393417a1a71a2c1fae4',
    messagingSenderId: '666971974381',
    projectId: 'flutter-gardabooking',
    storageBucket: 'flutter-gardabooking.appspot.com',
    iosClientId: '666971974381-rbbqiie4694vnq3qt0v3gb9utc0qqc8m.apps.googleusercontent.com',
    iosBundleId: 'henrikferrari.com.ecomrejsegarda',
  );
}
